DROP TABLE IF EXISTS query;

CREATE TABLE query (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  queryId TEXT NOT NULL,
  sightings TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);
